# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJbVAOA5iHgUhK6BO6cdUFttIB4ySxdw
"""

from google.colab import files
import pandas as pd #study data

uploaded=files.upload()

data = pd.read_csv("panel_dataset.csv")
data.head()

import pandas as pd
X = data[['stress','strain','yield_strength']]
y = data['label']

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier( n_estimators=100,
                               random_state=42 )

model.fit(X_train, y_train)

print("Training data:", len(X_train))
print("Testing data:", len(X_test))

prediction = model.predict(X_test)
print(prediction)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, prediction)

print("Accuracy:", accuracy*100)

new_panel = [[188,.38,191]]
result = model.predict(new_panel)

print("Panel health:", result[0])

if result[0] == "Broken":
   print("Halt panel possible defect")
else:
  print("Meeting standards")

stress = int(input("Enter stress: "))
strain = float(input("Enter strain: "))
yield_strength = int(input("Enter strength: "))

status = "Pass" if stress < yield_strength else "Broken"

print("\nPhysics check:", status)


new_panel = [[stress, strain, yield_strength]]
prediction = model.predict(new_panel)

print("Model prediction:", prediction[0])

if prediction[0] == "Pass":
    print("Meeting standards")
elif prediction[0] == "Broken":
    print("Halt panel possible defect")